name: npm publish
on:
  release:
    types: [published]
jobs:
  publish-npm:
    name: Build and Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
      - run: pnpm i --frozen-lockfile
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
      - run: pnpm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.YARN_TOKEN}}
