name: npm publish
on:
  release:
    types: [published]
jobs:
  publish-npm:
    name: Build and Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
      - run: pnpm i
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
      - run: pnpm publish --access=public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.YARN_TOKEN}}
